ottest: ottest.c
	../../../bin/oblivcc -O3 ottest.c -o ottest

# One could also directly use gcc like so:
# gcc ottest.c -I ../../../src/ext/oblivc -L ../../../obj/x86_LINUX/  \
#   -lobliv -lgcrypt -pthread -O3 -o ottest
