$(if $(testName),,$(error 'testName' must be defined before Makefile.simple is used))
CILPATH=../../../
CFLAGS=-O3
./a.out: $(testName).oc $(testName).c ../common/util.c $(CILPATH)/obj/x86_LINUX/libobliv.a
	$(CILPATH)/bin/oblivcc $(CFLAGS) -I . $(testName).oc $(testName).c ../common/util.c
clean:
	rm -f a.out $(testName).oc.cil.i $(testName).oc.i $(testName).oc.cil.c
